spring.application.name=demo

spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/demo

spring.security.user.name=teamproject12
spring.security.user.password=teamproject12

stripe.secret.key=sk_test_51T6tf5HjDjxFd3UCjpJ91uEhqAAj0hHKCnchYTe1tENmqLUSA0asdMdH19wQkOH5alIJE8ECsqUlptn6EYeBZORO00j7yMAioz
stripe.webhook.secret = hsec_329d33cf04fc9d9a31ac51a1757faabb0d416453ccd84209fcce5e2f64f24962

spring.datasource.username=oaxaca
spring.datasource.password=oaxaca
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true

server.address=0.0.0.0
server.port=8080
