spring.application.name=demo

spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/demo

spring.security.user.name=teamproject12
spring.security.user.password=teamproject12

stripe.secret.key=sk_test_51T6tf5HjDjxFd3UCTwZV8EnypA9GqX043QmA4Z9Uegu4YtTGeuPJLnPsLwcZt37CjdC3w2XSd7vLaPhJ1PNscOlm00YaX0Zkkn

spring.datasource.username=oaxaca
spring.datasource.password=oaxaca
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true

server.address=0.0.0.0
server.port=8080
