spring.application.name=demo

spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/demo

spring.security.user.name=teamproject12
spring.security.user.password=teamproject12

spring.datasource.username=oaxaca
spring.datasource.password=oaxaca
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.defer-datasource-initialization=true

